"""Initial

Revision ID: 53f18513b85a
Revises: 
Create Date: 2020-12-17 14:29:37.452384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f18513b85a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draw_requests',
    sa.Column('draw_request_id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('budget_item_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('draw_request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draw_requests')
    # ### end Alembic commands ###
