"""Initial migration

Revision ID: 18d52a2e18cf
Revises: 
Create Date: 2020-12-17 04:36:21.628447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d52a2e18cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('budget_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budgets')
    # ### end Alembic commands ###
